application.instance-name=${INSTANCE_NAME:notificaiton-instance-0}
spring.application.name=notification
spring.threads.virtual.enabled=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:8080}


spring.main.allow-bean-definition-overriding=true

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG